### ISSUE TITLE
lemmatizer bugs with harakat

### ISSUE THREAD

**Issue by Kentoseth** [linuxscout/qalsadi#3]
assalamu 3laykum,

There are some bugs with the lemmatizer function when using words that have harakat and the special 'standing' fat7a.

Here is a [link to download surah fati7a JSON](https://raw.githubusercontent.com/semarketir/quranjson/master/source/surah/surah_1.json)

The code I ran:
```
import json
import qalsadi.analex as qa
import qalsadi.lemmatizer

#for analex
debug=False;
limit=500
analyzer = qa.Analex()
analyzer.set_debug(debug);

#for lemma
lemmer = qalsadi.lemmatizer.Lemmatizer()
lemmer.set_vocalized_lemma()

with open('surah_1.json', 'r') as data_file:
    json_data = json.load(data_file)
    for verse in json_data['verse'].values():

        lemmas = lemmer.lemmatize_text(verse, return_pos=True)
        print(lemmas)
```

Lemma bugs:

 - Breaks words that have "ٱلرَّحْمَٰنِ" = 'standing' fat7a
 - does not split preposition from word (see the word bismi)
 - adds its own harakat even when harakat is provided (see the word 'rabb')
 - identifies many word-types incorrectly (not as noun/verb as expected)

Shukran.

**Comment by linuxscout** [comment]
وعليكم السلام ورحمة الله
> 
> #for lemma
> lemmer = qalsadi.lemmatizer.Lemmatizer()
> lemmer.set_vocalized_lemma()
> 
> with open('surah_1.json', 'r') as data_file:
>     json_data = json.load(data_file)
>     for verse in json_data['verse'].values():
> 
>         lemmas = lemmer.lemmatize_text(verse, return_pos=True)
>         print(lemmas)
> ```
> 
> Lemma bugs:
> 
>     * Breaks words that have "ٱلرَّحْمَٰنِ" = 'standing' fat7a

The lemmatizer is destined to Arabic standard script, where verses are written in Othmani script with special characters, you can normalize the verse text by removing some letters or convert them into standard letters like Alef Wasla into Alef, and Supscript Alef to Alef.

I will try to add this features into lemmatize and tokenizer.


This is not a bug,  You have selected the  to get a vocalized lemma, from word "رحمن",  which has a 
>     * does not split preposition from word (see the word bismi)
> 

The special script used in Quran write "Bism" as "بسم" where it written in standard script as "باسم",
the word "بسم" can be confused with "بسم" translated as "to smile"


>     * adds its own harakat even when harakat is provided (see the word 'rabb')

The vocalized output lemma  is written a an abstract form as "ربّ" with مرفوع تنوين.

>     * identifies many word-types incorrectly (not as noun/verb as expected)

The Lemmatizer give all possible lemmas and doesn't recognize context.
> 
> Shukran.

**Comment by linuxscout** [comment]
* I fixed the tokenizer for "stand Fatha", you may update "pip install --upgrade pyarabic"
* for lemmatizer, you must normalize some letters like "stand Fatha, Alef wasla, Madda" before analysis,
* I don't add default converter of "stand Fatha, Alef wasla, Madda", because some times this letters are used as esthetics diacritics, for example " الضَّآلِّينَ" or "الضحىٰ" then their behavior can vary.
*

**Comment by Kentoseth** [comment]
> for lemmatizer, you must normalize some letters like "stand Fatha, Alef wasla, Madda" before analysis,

For Alef Wasla, this isn't in pyArabic. I assume a simple find/replace using Python should fix this issue?

Shukran for the quick changes to the libraries.
